story: >
  写一个儿童故事，用于正面影响小朋友注意卫生。并且喜欢吃蔬菜。

# Save folder
root_save_folder: "outputs"
thumbnail_save_folder: "outputs/thumbnails"

# The number of sections or episodes in the story
num_sections: 3
section_length: 1000

# Comma-separated list of genres for the story
genres: "fantasy,scifi"

# The writing style to use for the story
writing_style: "third person"

# Whether to generate a thumbnail prompt for the story
gen_thumbnail: true

text_models:

  # The AI provider to use for generating the story, supported: DeepSeek, OpenAI, GROQ, Claude
  provider: "DeepSeek"

  # The specific language model to use, supported:
  # OpenAI: gpt-3.5-turbo-instruct, gpt-4o
  # DeepSeek: deep-seek-chat
  # GROQ: llama3-8b-8192, llama3-70b-8192, gemma2-9b-it, whisper-large-v3, mixtral-8x7b-32768
  # Claude: claude-3-5-sonnet-20240620, claude-3-opus-20240229, claude-3-haiku-20240307
  lm_name: "deep-seek-chat"
  # lm_name: "mixtral-8x7b-32768"
