story: >
  Generate a series of eposide for healing music scripts. The story content of each episode is the music generation prmopt.
  We want the topic of the story to be from the perspective of beautify earth forest.

# The number of sections or episodes in the story
num_sections: 4


# Comma-separated list of genres for the story
genres: "nature, forest, healing music, realistic"

# The writing style to use for the story
writing_style: "third person"

# Save folder, don't change until you know what you are doing
root_save_folder: "outputs"
log_folder: "logs"
log_level: INFO

# Whether to generate a thumbnail prompt for the story
image_model:
  gen_thumbnail: true
  thumbnail_save_folder: "thumbnails"
  thumbnail_generation_model: dall-e-2
  thumbnail_size: 512x512
  # thumbnail_generation_model: dall-e-3
  # thumbnail_size: 1024x1024
  thumbnail_quality: standard

text_model:
  # The maximum number of tokens to generate for the story
  section_length: 500

  # The AI provider to use for generating the story, supported: DeepSeek, OpenAI, GROQ, Claude
  provider: "OpenAI"

  # The specific language model to use, supported:
  # OpenAI: gpt-3.5-turbo-instruct, gpt-4o
  # DeepSeek: deep-seek-chat
  # GROQ: llama3-8b-8192, llama3-70b-8192, gemma2-9b-it, whisper-large-v3, mixtral-8x7b-32768
  # Claude: claude-3-5-sonnet-20240620, claude-3-opus-20240229, claude-3-haiku-20240307
  lm_name: "gpt-4o-mini"
  # lm_name: "mixtral-8x7b-32768"
